version: '3.3'
services:
  ide-api-node:
    image: node
    user: node
    container_name: ide-api-node
    links:
      - ide-api-mongodb
    volumes:
      - './:/home/node/app'
    working_dir: /home/node/app
    command: npm start
    depends_on:
      - ide-api-mongodb
  ide-api-nginx:
    image: nginx
    container_name: ide-api-nginx
    links:
      - ide-api-node
    ports:
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/ide-api.template'
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/ide-api.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - ide-api-node
  ide-api-mongodb:
    image: mongo
    container_name: ide-api-mongodb
    ports:
      - '27017:27017'
