version: '3.3'
services:
  ide-api-node:
    image: node
    user: node
    container_name: ide-api-node
    links:
      - ide-api-mongodb
    ports:
      - '8084:8084'
    volumes:
      - './:/home/node/app'
    working_dir: /home/node/app
    command: npm start
    depends_on:
        - ide-api-mongodb
  ide-api-mongodb:
    image: mongo
    container_name: ide-api-mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./data:/data/db
